{
 "title": "Applications",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Scrape duration sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"app-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk free bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "disk_free_bytes{job=\"app-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk total bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "disk_total_bytes{job=\"app-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jdbc connection max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "jdbc_connections_max{job=\"app-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Start sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "application_started_time_seconds{job=\"app-job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}