{
 "title": "JVM",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "loaded classes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{job=\"app-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{job=\"app-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gc count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_count{job=\"app-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"app-job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}