{
 "title": "Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total QPS max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"app-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor core threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "executor_pool_core_threads{job=\"app-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor active threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "executor_active_threads{job=\"app-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor remaining tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "executor_queue_remaining_tasks{job=\"app-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor size threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "executor_pool_size_threads{job=\"app-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"app-job\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor queue tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "executor_queued_tasks{job=\"app-job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}