services:
  app:
    # use parent dir Dockerfile build image
    build: ../../../
    # port transport
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=app
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mydatabase?useSSL=false&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_DATASOURCE_DATABASE=mydatabase
    depends_on:
      # 优先于 spring 启动
      - redis
      - mysql

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --web.enable-lifecycle
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    # prometheus datasource url: http://prometheus:9090
    # default auth: admin/admin
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      # grafana default config file path.
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_PATH_PROVISIONING=/etc/grafana/provisioning
      - GF_DASHBOARDS_PATH=/etc/grafana/provisioning/dashboards
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  redis-data:
  mysql_data: